heat_template_version: 2015-10-15

parameters:
  fw_name:
    type: string
  fw_image:
    type: string
  fw_flavor:
    type: string
  router_name:
    type: string
  mgmt_subnet_name:
    type: string
  trust_subnet_name:
    type: string
  untrust_subnet_name:
    type: string
  floating_subnet_name:
    type: string
  security_group_name:
    type: string
  server_image:
    type: string
  server_flavor:
    type: string
  server_trust_name:
    type: string
  server_untrust_name:
    type: string
   

resources:
  router:
    type: OS::Neutron::Router
    properties:
      name: { get_param: router_name }
      external_gateway_info:
        network: { get_param: floating_subnet_name  }

  mgmt_net:
    type: OS::Neutron::Net
    properties:
      name: { get_param: mgmt_subnet_name }

  mgmt_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: mgmt_net }
      cidr: 100.0.0.0/24
      gateway_ip: 100.0.0.1
 
  router_interface_mgmt:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }        
      subnet_id: { get_resource: mgmt_subnet }
             
  trust_net:
    type: OS::Neutron::Net
    properties:
      name: { get_param: trust_subnet_name }

  trust_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: trust_net }
      cidr: 10.10.10.0/24
      gateway_ip: 10.10.10.1
          
  router_interface_trust:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }      
      subnet_id: { get_resource: trust_subnet }

  untrust_net:
    type: OS::Neutron::Net
    properties:
      name: { get_param: untrust_subnet_name }

  untrust_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: untrust_net }
      cidr: 20.20.20.0/24
      gateway_ip: 20.20.20.1

  router_interface_untrust:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }       
      subnet_id: { get_resource: untrust_subnet }


  untrust_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      name: untrust_secgroup
      rules:
        - protocol: tcp
          port_range_min: 1
          port_range_max: 65535
          remote_ip_prefix: 0.0.0.0/0
          direction: ingress
        - protocol: tcp
          port_range_min: 1
          port_range_max: 65535
          remote_ip_prefix: 0.0.0.0/0
          direction: egress
        - protocol: udp
          port_range_min: 1
          port_range_max: 65535
          remote_ip_prefix: 0.0.0.0/0
          direction: ingress
        - protocol: udp
          port_range_min: 1
          port_range_max: 65535
          remote_ip_prefix: 0.0.0.0/0
          direction: egress
        - protocol: icmp
          remote_ip_prefix: 0.0.0.0/0
          direction: ingress
        - protocol: icmp
          remote_ip_prefix: 0.0.0.0/0
          direction: egress


  trust_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      name: trust_secgroup
      rules:
        - protocol: tcp
          port_range_min: 1
          port_range_max: 65535
          remote_ip_prefix: 0.0.0.0/0
          direction: ingress
        - protocol: tcp
          port_range_min: 1
          port_range_max: 65535
          remote_ip_prefix: 0.0.0.0/0
          direction: egress
        - protocol: udp
          port_range_min: 1
          port_range_max: 65535
          remote_ip_prefix: 0.0.0.0/0
          direction: ingress
        - protocol: udp
          port_range_min: 1
          port_range_max: 65535
          remote_ip_prefix: 0.0.0.0/0
          direction: egress
        - protocol: icmp
          remote_ip_prefix: 0.0.0.0/0
          direction: ingress
        - protocol: icmp
          remote_ip_prefix: 0.0.0.0/0
          direction: egress
      
      
  firewall_mgmt_nic:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: mgmt_net }
      security_groups:
        - { get_param: security_group_name }
      fixed_ips:
        - subnet_id: { get_resource: mgmt_subnet }
          ip_address: "100.0.0.3"
       
  firewall_trust_nic:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: trust_net }
      security_groups:
        - { get_resource: trust_secgroup }
      fixed_ips:
        - subnet_id: { get_resource: trust_subnet }
          ip_address: "10.10.10.3"
      value_specs:
        nuage_redirect_targets: {get_resource: fw_trust_redirect}

  firewall_untrust_nic:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: untrust_net }
      security_groups:
        - { get_resource: untrust_secgroup }
      fixed_ips:
        - subnet_id: { get_resource: untrust_subnet }
          ip_address: "20.20.20.3"
      value_specs:
        nuage_redirect_targets: {get_resource: fw_untrust_redirect}



  firewall:
    type: OS::Nova::Server
    properties:
        name: { get_param: fw_name }
        image: { get_param: fw_image }
        flavor: { get_param: fw_flavor }
        networks:
          - port: {get_resource: firewall_mgmt_nic}
          - port: {get_resource: firewall_untrust_nic}
          - port: {get_resource: firewall_trust_nic}
        user_data_format: RAW
        config_drive: true
        personality:
           /config/init-cfg.txt: {get_file: "/home/heat-admin/deployments/init-cfg.txt"}
#        /config/init-cfg.txt: { get_file: "http://web_server_name_ip/pan_bs/init-cfg.txt" }
           /config/bootstrap.xml: {get_file: "/home/heat-admin/deployments/init-cfg.txt"}
#        /config/bootstrap.xml: { get_file: "http://web_server_name_ip/pan_bs/bootstrap.xml" }
#        /license/authcodes: {get_file: "/opt/pan_bs/authcodes"}
#        /license/authcodes: {get_file: "http://web_server_name_ip/pan_bs/authcodes"}

  firewall_mgmt_fip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: floating_subnet_name }

  firewall_mgmt_floating_ip_assoc:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: firewall_mgmt_fip }
      port_id: { get_resource: firewall_mgmt_nic }


  fw_trust_redirect:
    type: Nuage::Neutron::RedirectTarget
    properties:
      insertion_mode: L3
      name: FW-TRUST-RT
      router_id: { get_resource: router }

  fw_untrust_redirect:
    type: Nuage::Neutron::RedirectTarget
    properties:
      insertion_mode: L3
      name: FW-UNTRUST-RT
      router_id: { get_resource: router }


  trust_to_untrust_redirect:
    type: Nuage::Neutron::RedirectTargetRule
    properties:
      action: REDIRECT
      origin_group_id: { get_resource: trust_secgroup}
      priority: 14
      protocol: 0 
      redirect_target_id: {get_resource: fw_trust_redirect}
      remote_group_id: { get_resource: untrust_secgroup}

  untrust_to_trust_redirect:
    type: Nuage::Neutron::RedirectTargetRule
    properties:
      action: REDIRECT
      origin_group_id: { get_resource: untrust_secgroup}
      priority: 15
      protocol: 0
      redirect_target_id: {get_resource: fw_untrust_redirect}
      remote_group_id: { get_resource: trust_secgroup}

  server_trust_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: trust_net }
      security_groups:
        - { get_param: security_group_name }
      fixed_ips:
        - subnet: { get_resource: trust_subnet }
          ip_address: "10.10.10.4"

  server_trust:
    type: OS::Nova::Server
    properties:
      name: { get_param: server_trust_name }
      image: { get_param: server_image }
      flavor: { get_param: server_flavor }
      networks:
        - port: { get_resource: server_trust_port }
        
  server_untrust_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: untrust_net }
      security_groups:
        - { get_param: security_group_name }
      fixed_ips:
        - subnet: { get_resource: untrust_subnet }
          ip_address: "20.20.20.4"       
          
  server_untrust:
    type: OS::Nova::Server
    properties:
      name: { get_param: server_untrust_name }    
      image: { get_param: server_image }
      flavor: { get_param: server_flavor }
      networks:
        - port: { get_resource: server_untrust_port }


outputs:
  fw_mgmt_fip:
    value: { get_attr: [firewall_mgmt_fip, floating_ip_address]}
  fw_trust_redirect:
    value: {get_resource: fw_trust_redirect}
  fw_unturst_redirect:
    value: {get_resource: fw_untrust_redirect}